urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("add-post/", views.add_post, name="add-post"),
    path("edit-post/<int:post_id>", views.edit_post, name="edit-post"),
    path("following/", views.following, name="following"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("follow/<int:user_id>", views.follow, name="follow"),
    path("unfollow/<int:user_id>", views.unfollow, name="unfollow"),
    path("likeunlike/<int:post_id>", views.likeunlike, name="likeunlike"),
]

models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Following(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import *

def index(request):
    posts = Post.objects.order_by('-created_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 10)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "network/index.html", {"posts": posts})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")


# add post utility
@login_required
def add_post(request):
    content = request.POST.get('content')
    user = request.user
    post = Post(user=user, content=content)
    post.save()
    messages.success(request, "Successfully posted new tweet")
    return redirect("index")

# edit post utility
@login_required
def edit_post(request, post_id):
    post = Post.objects.get(id=post_id)
    content = request.POST.get('content')
    post.content = content
    post.save()
    # messages.success(request, "Successfully updated the tweet")
    return JsonResponse({"status": True})


# profile page utility with pagination enabled with minimum of 2 posts.
def profile(request, user_id):
    user = User.objects.get(id=user_id)
    posts = user.posts.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "profile.html", {"user": user, "posts": posts})

# following utility.
@login_required
def following(request):
    user = User.objects.get(id=request.user.id)
    user_ids = Following.objects.filter(follower=user).values_list("user_id")
    posts = Post.objects.filter(user__in=user_ids)
    return render(request, "following.html", {"posts": posts})

# follow utility
@login_required
def follow(request, user_id):
    Following.objects.create(user_id=user_id, follower=request.user)
    messages.success(request, "Successfully followed the user")
    return redirect("profile", user_id=user_id)

# unfollow utility
@login_required
def unfollow(request, user_id):
    Following.objects.filter(user_id=user_id, follower=request.user).delete()
    messages.success(request, "Successfully unfollowed the user")
    return redirect("profile", user_id=user_id)

# like and unlike posts utility
def likeunlike(request, post_id):
    response = {
        "status": False,
        "message": "Please sign in to like"
    }
    if not request.user.is_authenticated:
        return JsonResponse(response)
    # unlike the post if user already liked and clicked on it again.
    if Like.objects.filter(user=request.user, post_id=post_id).exists():
        Like.objects.filter(user=request.user, post_id=post_id).delete()
        response['status'] = "unlike"
        response['message'] = "Successfully unliked the post"
        return JsonResponse(response)
    # like the post if user hasn't already liked it.
    Like.objects.create(user=request.user, post_id=post_id)
    response['status'] = "like"
    response['message'] = "Successfully liked the post"
    return JsonResponse(response)

templates/following.html
{% extends 'network/layout.html' %}

{% block body %}

    <h2>All posts by users</h2>
    <br>
    {% for post in posts %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'profile' post.user_id %}">
                    <h4>{{ post.user.username }}</h4>
                </a>
                {% if post.user.id == request.user.id %}
                    <a href="">Edit</a>
                {% endif %}
                <p>{{ post.content }}</p>
                <p>{{ post.created_at }}</p>
                <i class="fa fa-heart" aria-hidden="true" style="color: red"></i> 0
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
    <h2>All Posts</h2>
    {% if user.is_authenticated %}
    <form action="{% url 'add-post' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">New Post:</label>
            <textarea class="form-control" required name="content" placeholder="Write text.." id="content"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
    {% endif %}
    <br>
    {% for post in posts %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'profile' post.user_id %}">
                    <h4>{{ post.user.username }}</h4>
                </a>
                {% if post.user.id == request.user.id %}
                    <div>
                        <a href="javascript:void(0)" class="edit" data-id="{{ post.id }}">Edit</a>
                        <div class="edit-post-div hidden" id="post{{ post.id }}">
                            <form action="{% url 'add-post' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="edit-content{{ post.id }}">Edit Post:</label>
                                    <textarea class="form-control" required name="content" placeholder="Write text.."
                                              id="edit-content{{ post.id }}">{{ post.content }}</textarea>
                                </div>
                                <button type="button" data-id="{{ post.id }}" class="btn btn-primary update-post">Save
                                </button>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <div class="post">
                    <p id="post-content{{ post.id }}">{{ post.content }}</p>
                    <p>{{ post.created_at }}</p>
                </div>
                <i class="fa fa-heart like" data-id="{{ post.id }}"
                   style="cursor: pointer"> {{ post.like_set.count }}</i>
            </div>
        </div>
    {% endfor %}

    {% if posts.has_other_pages %}
        <nav aria-label="Page navigation conatiner" style="margin-top: 20px"></nav>
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
                <li class="page-link"><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled page-link"><span>&laquo;</span></li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li class="active page-link"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li class="page-link"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if posts.has_next %}
                <li class="page-link"><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled page-link"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Social Network{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Network</a>

    <div>
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">All Posts</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'following' %}">Following</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="body container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="{% static 'network/custom.js' %}"></script>
</body>
</html>

templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

templates/profile.html
{% extends 'network/layout.html' %}
{% load is_following %}

{% block body %}

    <div class="row mb-3 mt-3">
        <div class="col-md-12">
            <div class="d-flex flex-row border rounded">
                <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left">
                    <h4 class="text-primary">{{ user.username }}</h4>
                    Followers: {{ user.followers.count }}
                    Following: {{ user.following_set.count }}
                    <p>
                        {% if request.user.is_authenticated and user.id == request.user.id %}
                            <a href="#" class="btn btn-success" disabled>Follow</a>
                        {% else %}
                            {% if request.user.is_authenticated %}
                                {% is_following user as following %}
                                {% if not following %}
                                    <a href="{% url 'follow' user.id %}" class="btn btn-success">Follow</a>
                                {% else %}
                                    <a href="{% url 'unfollow' user.id %}" class="btn btn-danger">Un-follow</a>
                                {% endif %}
                            {% else %}
                                <p>Please login to follow</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
            </div>
            <h4 class="mt-4">Posts by the user</h4>
            {% for post in posts %}
                <div class="card">
                    <div class="card-body">
                        <h4>{{ post.user.username }}</h4>
                        {% if post.user.id == request.user.id %}
                            <a href="javascript:void(0)" class="edit">Edit</a>
                            <div class="edit-post-div hidden">
                                <form action="{% url 'add-post' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="edit-content">Edit Post:</label>
                                        <textarea class="form-control" required name="content"
                                                  placeholder="Write text.."
                                                  id="edit-content">{{ post.content }}</textarea>
                                    </div>
                                    <button type="button" data-id="{{ post.id }}" class="btn btn-primary update-post">
                                        Save
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                        <div class="post">
                            <p id="post-content">{{ post.content }}</p>
                            <p>{{ post.created_at }}</p>
                        </div>
                        <i class="fa fa-heart like" data-id="{{ post.id }}"
                           style="cursor: pointer"> {{ post.like_set.count }}</i>
                    </div>
                </div>
            {% endfor %}

            {% if posts.has_other_pages %}
                <nav aria-label="Page navigation conatiner" style="margin-top: 20px"></nav>
                <ul class="pagination justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-link"><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled page-link"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                        {% if posts.number == i %}
                            <li class="active page-link"><span>{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-link"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-link"><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled page-link"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>

{% endblock %}